<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // KELLYS NOID
        DB::table('products')->insert([
            'main_category_id' => 1,
            'sub_category_id' => 1,
            'price' => 3500,
            'producer' => 'Kellys',
            'model' => 'Noid',
            'model_year' => 2023,
            'frame' => 'hliník',
            'fork_type' => 'vzduchová',
            'frame_size' => 'L',
            'front_lift' => 150,
            'fork' => 'RockShox',
            'rear_shock' => 'RockShox',
            'front_tire' => 'Schwalbe',
            'rear_tire' => 'Schwalbe',
            'rim' => '29  DT Swiss',
            'cassette_count' => 12,
            'front_cassette_count' => 1,
            'chain' => 'Sram',
            'drive_train' => 'Sram',
            'cranks' => 'Sram',
            'cassette' => 'Sram',
            'derailleur' => 'Sram',
            'brakes' => 'Shimano',
            'front_rotor' => 'Shimano 180mm',
            'rear_rotor' =>'Shimano 180mm',
            'stem' => 'Kellys',
            'handbar' => 'Kellys',
            'grip' => 'Kellys',
            'seat_post' => 'RockShox',
            'seat' => 'Kellys',
            'is_new' => false,
            'is_offer_of_the_week' => false,
            'created_at' => Carbon::now(timezone: true),
            'updated_at' => Carbon::now(timezone: true)
        ]);

        // CTM MONS
        DB::table('products')->insert([
            'main_category_id' => 1,
            'sub_category_id' => 1,
            'price' => 3700,
            'producer' => 'CTM',
            'model' => 'Mons',
            'model_year' => 2023,
            'frame' => 'hliník',
            'fork_type' => 'vzduchová',
            'frame_size' => 'XL',
            'front_lift' => 150,
            'fork' => 'RockShox',
            'rear_shock' => 'RockShox',
            'front_tire' => 'Schwalbe',
            'rear_tire' => 'Schwalbe',
            'rim' => '29  DT Swiss',
            'cassette_count' => 12,
            'front_cassette_count' => 1,
            'chain' => 'Sram',
            'drive_train' => 'Sram',
            'cranks' => 'Sram',
            'cassette' => 'Sram',
            'derailleur' => 'Sram',
            'brakes' => 'Shimano',
            'front_rotor' => 'Shimano 180mm',
            'rear_rotor' =>'Shimano 180mm',
            'stem' => 'Kellys',
            'handbar' => 'Kellys',
            'grip' => 'Kellys',
            'seat_post' => 'RockShox',
            'seat' => 'Kellys',
            'is_new' => false,
            'is_offer_of_the_week' => false,
            'created_at' => Carbon::now(timezone: true),
            'updated_at' => Carbon::now(timezone: true)
        ]);

        // MONDRAKER FOXY
        DB::table('products')->insert([
            'main_category_id' => 1,
            'sub_category_id' => 1,
            'price' => 4500,
            'producer' => 'Mondraker',
            'model' => 'Foxy',
            'model_year' => 2023,
            'frame' => 'hliník',
            'fork_type' => 'vzduchová',
            'frame_size' => 'XL',
            'front_lift' => 150,
            'fork' => 'RockShox',
            'rear_shock' => 'RockShox',
            'front_tire' => 'Schwalbe',
            'rear_tire' => 'Schwalbe',
            'rim' => '29  DT Swiss',
            'cassette_count' => 12,
            'front_cassette_count' => 1,
            'chain' => 'Sram',
            'drive_train' => 'Sram',
            'cranks' => 'Sram',
            'cassette' => 'Sram',
            'derailleur' => 'Sram',
            'brakes' => 'Shimano',
            'front_rotor' => 'Shimano 180mm',
            'rear_rotor' =>'Shimano 180mm',
            'stem' => 'Kellys',
            'handbar' => 'Kellys',
            'grip' => 'Kellys',
            'seat_post' => 'RockShox',
            'seat' => 'Kellys',
            'is_new' => false,
            'is_offer_of_the_week' => false,
            'created_at' => Carbon::now(timezone: true),
            'updated_at' => Carbon::now(timezone: true)
        ]);

        // SANTA CRUZ V10 - RED
        DB::table('products')->insert([
            'main_category_id' => 1,
            'sub_category_id' => 1,
            'price' => 4999,
            'producer' => 'Santa Cruz',
            'model' => 'V10',
            'model_year' => 2023,
            'frame' => 'hliník',
            'fork_type' => 'vzduchová',
            'frame_size' => 'L',
            'front_lift' => 150,
            'fork' => 'RockShox',
            'rear_shock' => 'RockShox',
            'front_tire' => 'Schwalbe',
            'rear_tire' => 'Schwalbe',
            'rim' => '29  DT Swiss',
            'cassette_count' => 12,
            'front_cassette_count' => 1,
            'chain' => 'Sram',
            'drive_train' => 'Sram',
            'cranks' => 'Sram',
            'cassette' => 'Sram',
            'derailleur' => 'Sram',
            'brakes' => 'Shimano',
            'front_rotor' => 'Shimano 180mm',
            'rear_rotor' =>'Shimano 180mm',
            'stem' => 'Kellys',
            'handbar' => 'Kellys',
            'grip' => 'Kellys',
            'seat_post' => 'RockShox',
            'seat' => 'Kellys',
            'is_new' => false,
            'is_offer_of_the_week' => false,
            'created_at' => Carbon::now(timezone: true),
            'updated_at' => Carbon::now(timezone: true)
        ]);

        // SANTA CRUZ V10 - BLACK
        DB::table('products')->insert([
            'main_category_id' => 1,
            'sub_category_id' => 1,
            'price' => 4799,
            'producer' => 'Santa Cruz',
            'model' => 'V10',
            'model_year' => 2023,
            'frame' => 'hliník',
            'fork_type' => 'vzduchová',
            'frame_size' => 'M',
            'front_lift' => 150,
            'fork' => 'RockShox',
            'rear_shock' => 'RockShox',
            'front_tire' => 'Schwalbe',
            'rear_tire' => 'Schwalbe',
            'rim' => '27.5 DT Swiss',
            'cassette_count' => 12,
            'front_cassette_count' => 1,
            'chain' => 'Sram',
            'drive_train' => 'Sram',
            'cranks' => 'Sram',
            'cassette' => 'Sram',
            'derailleur' => 'Sram',
            'brakes' => 'Shimano',
            'front_rotor' => 'Shimano 180mm',
            'rear_rotor' =>'Shimano 180mm',
            'stem' => 'Kellys',
            'handbar' => 'Kellys',
            'grip' => 'Kellys',
            'seat_post' => 'RockShox',
            'seat' => 'Kellys',
            'is_new' => false,
            'is_offer_of_the_week' => false,
            'created_at' => Carbon::now(timezone: true),
            'updated_at' => Carbon::now(timezone: true)
        ]);









        // KELLYS SWAG
        DB::table('products')->insert([
            'main_category_id' => 1,
            'sub_category_id' => 2,
            'price' => 1500,
            'producer' => 'Kellys',
            'model' => 'Swag',
            'model_year' => 2019,
            'frame' => 'hliník',
            'fork_type' => 'vzduchová',
            'frame_size' => 'L',
            'front_lift' => 160,
            'fork' => 'RockShox',
            'rear_shock' => 'RockShox',
            'front_tire' => 'Schwalbe',
            'rear_tire' => 'Schwalbe',
            'rim' => '27.5 DT Swiss',
            'cassette_count' => 12,
            'front_cassette_count' => 1,
            'chain' => 'Sram',
            'drive_train' => 'Sram',
            'cranks' => 'Sram',
            'cassette' => 'Sram',
            'derailleur' => 'Sram',
            'brakes' => 'Shimano',
            'front_rotor' => 'Shimano 180mm',
            'rear_rotor' =>'Shimano 180mm',
            'stem' => 'Kellys',
            'handbar' => 'Kellys',
            'grip' => 'Kellys',
            'seat_post' => 'RockShox',
            'seat' => 'Kellys',
            'is_new' => true,
            'is_offer_of_the_week' => false,
            'created_at' => Carbon::now(timezone: true),
            'updated_at' => Carbon::now(timezone: true)
        ]);

        // CTM SCROLL
        DB::table('products')->insert([
            'main_category_id' => 1,
            'sub_category_id' => 2,
            'price' => 1800,
            'producer' => 'CTM',
            'model' => 'Scroll',
            'model_year' => 2022,
            'frame' => 'hliník',
            'fork_type' => 'vzduchová',
            'frame_size' => 'M',
            'front_lift' => 150,
            'fork' => 'RockShox',
            'rear_shock' => 'RockShox',
            'front_tire' => 'Schwalbe',
            'rear_tire' => 'Schwalbe',
            'rim' => '29  DT Swiss',
            'cassette_count' => 12,
            'front_cassette_count' => 1,
            'chain' => 'Sram',
            'drive_train' => 'Sram',
            'cranks' => 'Sram',
            'cassette' => 'Sram',
            'derailleur' => 'Sram',
            'brakes' => 'Shimano',
            'front_rotor' => 'Shimano 180mm',
            'rear_rotor' =>'Shimano 180mm',
            'stem' => 'Kellys',
            'handbar' => 'Kellys',
            'grip' => 'Kellys',
            'seat_post' => 'RockShox',
            'seat' => 'Kellys',
            'is_new' => true,
            'is_offer_of_the_week' => true,
            'created_at' => Carbon::now(timezone: true),
            'updated_at' => Carbon::now(timezone: true)
        ]);

        // MONDRAKER SUPERFOXY
        DB::table('products')->insert([
            'main_category_id' => 1,
            'sub_category_id' => 2,
            'price' => 2500,
            'producer' => 'Mondraker',
            'model' => 'Superfoxy',
            'model_year' => 2021,
            'frame' => 'hliník',
            'fork_type' => 'vzduchová',
            'frame_size' => 'XL',
            'front_lift' => 150,
            'fork' => 'RockShox',
            'rear_shock' => 'RockShox',
            'front_tire' => 'Schwalbe',
            'rear_tire' => 'Schwalbe',
            'rim' => '29  DT Swiss',
            'cassette_count' => 12,
            'front_cassette_count' => 1,
            'chain' => 'Sram',
            'drive_train' => 'Sram',
            'cranks' => 'Sram',
            'cassette' => 'Sram',
            'derailleur' => 'Sram',
            'brakes' => 'Shimano',
            'front_rotor' => 'Shimano 180mm',
            'rear_rotor' =>'Shimano 180mm',
            'stem' => 'Kellys',
            'handbar' => 'Kellys',
            'grip' => 'Kellys',
            'seat_post' => 'RockShox',
            'seat' => 'Kellys',
            'is_new' => true,
            'is_offer_of_the_week' => true,
            'created_at' => Carbon::now(timezone: true),
            'updated_at' => Carbon::now(timezone: true)
        ]);

        // SANTA CRUZ MEGATOWER - RED
        DB::table('products')->insert([
            'main_category_id' => 1,
            'sub_category_id' => 2,
            'price' => 3299,
            'producer' => 'Santa Cruz',
            'model' => 'Megatower',
            'model_year' => 2023,
            'frame' => 'hliník',
            'fork_type' => 'vzduchová',
            'frame_size' => 'S',
            'front_lift' => 150,
            'fork' => 'RockShox',
            'rear_shock' => 'RockShox',
            'front_tire' => 'Schwalbe',
            'rear_tire' => 'Schwalbe',
            'rim' => '27.5 DT Swiss',
            'cassette_count' => 12,
            'front_cassette_count' => 1,
            'chain' => 'Sram',
            'drive_train' => 'Sram',
            'cranks' => 'Sram',
            'cassette' => 'Sram',
            'derailleur' => 'Sram',
            'brakes' => 'Shimano',
            'front_rotor' => 'Shimano 180mm',
            'rear_rotor' =>'Shimano 180mm',
            'stem' => 'Kellys',
            'handbar' => 'Kellys',
            'grip' => 'Kellys',
            'seat_post' => 'RockShox',
            'seat' => 'Kellys',
            'is_new' => false,
            'is_offer_of_the_week' => false,
            'created_at' => Carbon::now(timezone: true),
            'updated_at' => Carbon::now(timezone: true)
        ]);

        // SANTA CRUZ MEGATOWER - GRAY
        DB::table('products')->insert([
            'main_category_id' => 1,
            'sub_category_id' => 2,
            'price' => 3300,
            'producer' => 'Santa Cruz',
            'model' => 'Megatower',
            'model_year' => 2023,
            'frame' => 'hliník',
            'fork_type' => 'vzduchová',
            'frame_size' => 'M',
            'front_lift' => 150,
            'fork' => 'RockShox',
            'rear_shock' => 'RockShox',
            'front_tire' => 'Schwalbe',
            'rear_tire' => 'Schwalbe',
            'rim' => '29  DT Swiss',
            'cassette_count' => 12,
            'front_cassette_count' => 1,
            'chain' => 'Sram',
            'drive_train' => 'Sram',
            'cranks' => 'Sram',
            'cassette' => 'Sram',
            'derailleur' => 'Sram',
            'brakes' => 'Shimano',
            'front_rotor' => 'Shimano 180mm',
            'rear_rotor' =>'Shimano 180mm',
            'stem' => 'Kellys',
            'handbar' => 'Kellys',
            'grip' => 'Kellys',
            'seat_post' => 'RockShox',
            'seat' => 'Kellys',
            'is_new' => false,
            'is_offer_of_the_week' => false,
            'created_at' => Carbon::now(timezone: true),
            'updated_at' => Carbon::now(timezone: true)
        ]);

        // PIVOT SWITCHBLADE
        DB::table('products')->insert([
            'main_category_id' => 1,
            'sub_category_id' => 2,
            'price' => 2750,
            'producer' => 'Pivot',
            'model' => 'Switchblade',
            'model_year' => 2023,
            'frame' => 'hliník',
            'fork_type' => 'vzduchová',
            'frame_size' => 'M',
            'front_lift' => 150,
            'fork' => 'RockShox',
            'rear_shock' => 'RockShox',
            'front_tire' => 'Schwalbe',
            'rear_tire' => 'Schwalbe',
            'rim' => '27.5 DT Swiss',
            'cassette_count' => 12,
            'front_cassette_count' => 1,
            'chain' => 'Sram',
            'drive_train' => 'Sram',
            'cranks' => 'Sram',
            'cassette' => 'Sram',
            'derailleur' => 'Sram',
            'brakes' => 'Shimano',
            'front_rotor' => 'Shimano 180mm',
            'rear_rotor' =>'Shimano 180mm',
            'stem' => 'Kellys',
            'handbar' => 'Kellys',
            'grip' => 'Kellys',
            'seat_post' => 'RockShox',
            'seat' => 'Kellys',
            'is_new' => false,
            'is_offer_of_the_week' => false,
            'created_at' => Carbon::now(timezone: true),
            'updated_at' => Carbon::now(timezone: true)
        ]);
    }
}